import { BellRing, ShieldAlert, X } from 'lucide-react-native';
import { Modal, Pressable, StyleSheet, Text, View } from 'react-native';
import { colors, shadow } from '@/lib/theme';

export function AlertOverlay({ visible, onDismiss }: { visible: boolean; onDismiss: () => void }) {
  return <Modal transparent visible={visible} animationType="fade"><View style={styles.backdrop}><View style={[styles.card, shadow]}><View style={styles.icon}><ShieldAlert size={32} color={colors.red} strokeWidth={2.5} /></View><View style={styles.close}><Pressable onPress={onDismiss}><X size={19} color={colors.muted} /></Pressable></View><Text style={styles.kicker}>SAFETY ALERT</Text><Text style={styles.title}>High-risk zone ahead</Text><Text style={styles.body}>You have entered a high-risk hazard zone. Proceed with extreme caution, reduce speed, and keep extra distance.</Text><View style={styles.zone}><BellRing size={17} color={colors.red} /><Text style={styles.zoneText}>RED ZONE · HAZARD REACHED</Text></View><Pressable onPress={onDismiss} style={styles.button}><Text style={styles.buttonText}>I understand</Text></Pressable></View></View></Modal>;
}

const styles = StyleSheet.create({ backdrop: { flex: 1, backgroundColor: 'rgba(16,32,28,.58)', justifyContent: 'center', padding: 24 }, card: { backgroundColor: '#fff', borderRadius: 28, padding: 26, alignItems: 'center' }, icon: { width: 68, height: 68, borderRadius: 34, backgroundColor: colors.redSoft, justifyContent: 'center', alignItems: 'center', marginBottom: 18 }, close: { position: 'absolute', top: 17, right: 17, padding: 5 }, kicker: { color: colors.red, fontSize: 11, letterSpacing: 1.8, fontWeight: '900' }, title: { color: colors.ink, fontWeight: '900', fontSize: 27, marginTop: 9, textAlign: 'center' }, body: { color: colors.muted, fontSize: 15, lineHeight: 23, textAlign: 'center', marginTop: 12 }, zone: { backgroundColor: colors.redSoft, flexDirection: 'row', alignItems: 'center', gap: 8, paddingHorizontal: 14, paddingVertical: 11, borderRadius: 12, marginTop: 20 }, zoneText: { color: colors.red, fontWeight: '900', fontSize: 11, letterSpacing: .7 }, button: { backgroundColor: colors.ink, width: '100%', height: 50, borderRadius: 14, justifyContent: 'center', alignItems: 'center', marginTop: 22 }, buttonText: { color: '#fff', fontWeight: '800', fontSize: 15 } });
