import React, { useState } from 'react';
import { Check, ChevronRight, CircleAlert, Star } from 'lucide-react-native';
import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { colors } from '@/lib/theme';

export function FeedbackSheet({ onSubmit }: { onSubmit: (rating: number, hazard: boolean, note: string) => void }) {
  const [rating, setRating] = useState(4);
  const [hazard, setHazard] = useState(false);
  const [note, setNote] = useState('');
  const [submitting, setSubmitting] = useState(false);
  return <View style={styles.sheet}><View style={styles.handle} /><Text style={styles.kicker}>TRIP COMPLETE</Text><Text style={styles.title}>How was the road?</Text><Text style={styles.subtitle}>Your report helps make the next drive safer.</Text><View style={styles.stars}>{[1,2,3,4,5].map((item) => <Pressable key={item} onPress={() => setRating(item)}><Star size={27} color={item <= rating ? colors.yellow : colors.line} fill={item <= rating ? colors.yellow : 'transparent'} /></Pressable>)}</View><Pressable onPress={() => setHazard(!hazard)} style={[styles.report, hazard && styles.reportActive]}><CircleAlert size={19} color={hazard ? colors.red : colors.muted} /><Text style={[styles.reportText, hazard && { color: colors.red }]}>I noticed a new hazard</Text><View style={[styles.check, hazard && styles.checkActive]}>{hazard && <Check size={13} color="#fff" />}</View></Pressable>{hazard && <TextInput value={note} onChangeText={setNote} placeholder="Tell us what you saw..." placeholderTextColor={colors.muted} style={styles.input} multiline /> }<Pressable disabled={submitting} onPress={() => { setSubmitting(true); onSubmit(rating, hazard, note); }} style={[styles.button, submitting && { opacity: 0.6 }]}><Text style={styles.buttonText}>{submitting ? 'Submitting...' : 'Submit road report'}</Text><ChevronRight size={18} color="#fff" /></Pressable></View>;
}

const styles = StyleSheet.create({ sheet: { backgroundColor: colors.surface, borderRadius: 26, padding: 22, marginTop: 18 }, handle: { height: 4, width: 40, borderRadius: 3, backgroundColor: colors.line, alignSelf: 'center', marginBottom: 22 }, kicker: { color: colors.teal, fontSize: 11, letterSpacing: 1.6, fontWeight: '900' }, title: { color: colors.ink, fontWeight: '900', fontSize: 25, marginTop: 7 }, subtitle: { color: colors.muted, marginTop: 7, fontSize: 14 }, stars: { flexDirection: 'row', gap: 12, marginVertical: 20 }, report: { borderWidth: 1, borderColor: colors.line, borderRadius: 14, padding: 14, flexDirection: 'row', alignItems: 'center', gap: 10 }, reportActive: { borderColor: colors.red, backgroundColor: colors.redSoft }, reportText: { color: colors.ink, fontWeight: '700', flex: 1 }, check: { height: 22, width: 22, borderRadius: 6, borderWidth: 1, borderColor: colors.line }, checkActive: { backgroundColor: colors.red, borderColor: colors.red, alignItems: 'center', justifyContent: 'center' }, input: { borderWidth: 1, borderColor: colors.line, borderRadius: 13, minHeight: 70, marginTop: 12, padding: 12, color: colors.ink, textAlignVertical: 'top' }, button: { backgroundColor: colors.teal, height: 50, borderRadius: 14, justifyContent: 'center', alignItems: 'center', flexDirection: 'row', gap: 5, marginTop: 16 }, buttonText: { color: '#fff', fontWeight: '800', fontSize: 15 } });
