import { AlertTriangle, LocateFixed, MapPin, Navigation } from 'lucide-react-native';
import { StyleSheet, Text, View } from 'react-native';
import Svg, { Circle, Path, Rect } from 'react-native-svg';
import { colors } from '@/lib/theme';

export function RiskMap({ destination }: { destination: string }) {
  return <View style={styles.wrap}><View style={styles.map}><View style={styles.grid} /><Svg width="100%" height="100%" viewBox="0 0 360 280" style={StyleSheet.absoluteFill}><Path d="M-20 228 C 54 186, 91 229, 151 174 S 244 59, 383 78" fill="none" stroke={colors.green} strokeWidth="28" opacity=".20" /><Path d="M-20 228 C 54 186, 91 229, 151 174 S 244 59, 383 78" fill="none" stroke={colors.green} strokeWidth="10" opacity=".95" /><Path d="M147 177 C 191 139, 207 84, 247 72" fill="none" stroke={colors.yellow} strokeWidth="11" opacity=".95" /><Path d="M239 76 C 262 65, 294 69, 384 78" fill="none" stroke={colors.red} strokeWidth="13" opacity=".95" /><Circle cx="47" cy="211" r="11" fill="#fff" stroke={colors.teal} strokeWidth="4" /><Circle cx="329" cy="76" r="11" fill="#fff" stroke={colors.red} strokeWidth="4" /><Circle cx="213" cy="111" r="14" fill={colors.yellowSoft} stroke={colors.yellow} strokeWidth="3" /><Circle cx="279" cy="69" r="14" fill={colors.redSoft} stroke={colors.red} strokeWidth="3" /></Svg><View style={styles.startLabel}><LocateFixed size={13} color={colors.teal} /><Text style={styles.labelText}>YOU</Text></View><View style={styles.destLabel}><Navigation size={13} color={colors.red} /><Text style={[styles.labelText, { color: colors.red }]}>{destination || 'DESTINATION'}</Text></View><View style={styles.hazardOne}><AlertTriangle size={14} color={colors.yellow} /></View><View style={styles.hazardTwo}><AlertTriangle size={14} color={colors.red} /></View><View style={styles.zoom}><Text style={styles.zoomText}>+</Text><View style={styles.zoomLine} /><Text style={styles.zoomText}>−</Text></View></View><View style={styles.legend}><Legend color={colors.green} label="Clear" /><Legend color={colors.yellow} label="Moderate risk" /><Legend color={colors.red} label="High risk" /></View></View>;
}

function Legend({ color, label }: { color: string; label: string }) { return <View style={styles.legendItem}><View style={[styles.legendDot, { backgroundColor: color }]} /><Text style={styles.legendText}>{label}</Text></View>; }

const styles = StyleSheet.create({ wrap: { backgroundColor: colors.surface, borderRadius: 24, overflow: 'hidden', marginBottom: 18 }, map: { height: 280, backgroundColor: '#EAF0E8', overflow: 'hidden' }, grid: { ...StyleSheet.absoluteFillObject, opacity: 0.25, backgroundColor: '#EAF0E8' }, startLabel: { position: 'absolute', left: 29, top: 185, flexDirection: 'row', alignItems: 'center', gap: 3, backgroundColor: '#fff', paddingHorizontal: 7, paddingVertical: 4, borderRadius: 8 }, destLabel: { position: 'absolute', right: 14, top: 46, flexDirection: 'row', alignItems: 'center', gap: 3, backgroundColor: '#fff', paddingHorizontal: 7, paddingVertical: 4, borderRadius: 8 }, labelText: { fontSize: 9, fontWeight: '900', color: colors.teal }, hazardOne: { position: 'absolute', left: '57%', top: '34%', backgroundColor: '#fff', borderRadius: 16, padding: 7 }, hazardTwo: { position: 'absolute', left: '75%', top: '17%', backgroundColor: '#fff', borderRadius: 16, padding: 7 }, zoom: { position: 'absolute', right: 13, bottom: 13, backgroundColor: '#fff', borderRadius: 10, alignItems: 'center', paddingVertical: 4, width: 30 }, zoomText: { color: colors.ink, fontWeight: '700', fontSize: 19, lineHeight: 22 }, zoomLine: { height: 1, backgroundColor: colors.line, width: 18 }, legend: { flexDirection: 'row', padding: 14, gap: 16 }, legendItem: { flexDirection: 'row', alignItems: 'center', gap: 6 }, legendDot: { width: 8, height: 8, borderRadius: 4 }, legendText: { color: colors.muted, fontSize: 11, fontWeight: '700' } });
