import { useEffect, useState } from 'react';
import { AlertTriangle, CheckCircle2, ChevronRight, Clock3, FileText, MapPin } from 'lucide-react-native';
import { StyleSheet, Text, View } from 'react-native';
import { Screen } from '@/components/Screen';
import { SectionHeader } from '@/components/SectionHeader';
import { supabase } from '@/lib/supabase';
import { colors, shadow } from '@/lib/theme';
import type { HazardReport } from '@/types/safepath';

export default function Reports() { const [reports, setReports] = useState<HazardReport[]>([]); useEffect(() => { supabase.from('hazard_reports').select('id,hazard_type,severity,description,status,created_at').order('created_at', { ascending: false }).limit(10).then(({ data }) => setReports((data as HazardReport[]) ?? [])); }, []); return <Screen><SectionHeader eyebrow="COMMUNITY SIGNAL" title="Road reports" action="How it works" /><View style={styles.summary}><View style={styles.summaryIcon}><FileText size={22} color={colors.teal} /></View><View style={styles.summaryCopy}><Text style={styles.summaryTitle}>Your reports make roads smarter</Text><Text style={styles.summaryBody}>Every verified signal improves safety for the next traveler.</Text></View></View><Text style={styles.sectionLabel}>RECENT COMMUNITY ACTIVITY</Text>{reports.length === 0 ? <View style={styles.empty}><CheckCircle2 size={25} color={colors.green} /><Text style={styles.emptyTitle}>No reports yet</Text><Text style={styles.emptyBody}>Complete a trip and share what you saw on the road.</Text></View> : reports.map((report) => <ReportRow key={report.id} report={report} />)}<Text style={styles.sectionLabel}>SIGNAL QUALITY</Text><View style={styles.quality}><View style={styles.qualityTop}><Text style={styles.qualityTitle}>Your contribution score</Text><Text style={styles.score}>—</Text></View><Text style={styles.qualityBody}>Submit your first road report to start building trust in the network.</Text><View style={styles.progress}><View style={styles.progressFill} /></View></View></Screen>; }
function ReportRow({ report }: { report: HazardReport }) { const isRed = report.severity === 'red'; return <View style={[styles.report, shadow]}><View style={[styles.reportIcon, { backgroundColor: isRed ? colors.redSoft : colors.yellowSoft }]}><AlertTriangle size={18} color={isRed ? colors.red : colors.yellow} /></View><View style={styles.reportCopy}><Text style={styles.reportTitle}>{report.hazard_type.replace('_', ' ')} reported</Text><View style={styles.meta}><Clock3 size={12} color={colors.muted} /><Text style={styles.metaText}>Recently · </Text><Text style={[styles.status, { color: report.status === 'verified' ? colors.green : colors.yellow }]}>{report.status}</Text></View></View><ChevronRight size={17} color={colors.muted} /></View>; }
const styles = StyleSheet.create({ summary: { backgroundColor: colors.ink, borderRadius: 22, padding: 19, flexDirection: 'row', alignItems: 'center', gap: 13, marginBottom: 28 }, summaryIcon: { width: 45, height: 45, borderRadius: 15, backgroundColor: '#DDF1EF', alignItems: 'center', justifyContent: 'center' }, summaryCopy: { flex: 1 }, summaryTitle: { color: '#fff', fontWeight: '800', fontSize: 15 }, summaryBody: { color: '#B7C9C4', fontSize: 12, lineHeight: 17, marginTop: 4 }, sectionLabel: { color: colors.muted, fontSize: 11, letterSpacing: 1.4, fontWeight: '900', marginBottom: 11 }, report: { backgroundColor: colors.surface, borderRadius: 17, padding: 13, flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 10 }, reportIcon: { width: 40, height: 40, borderRadius: 13, alignItems: 'center', justifyContent: 'center' }, reportCopy: { flex: 1 }, reportTitle: { color: colors.ink, fontWeight: '800', textTransform: 'capitalize', fontSize: 14 }, meta: { flexDirection: 'row', alignItems: 'center', marginTop: 5 }, metaText: { color: colors.muted, fontSize: 11, marginLeft: 4 }, status: { fontSize: 11, fontWeight: '800' }, empty: { backgroundColor: colors.surface, borderRadius: 18, padding: 28, alignItems: 'center', marginBottom: 28 }, emptyTitle: { color: colors.ink, fontWeight: '800', fontSize: 16, marginTop: 10 }, emptyBody: { color: colors.muted, fontSize: 13, textAlign: 'center', lineHeight: 19, marginTop: 5 }, quality: { backgroundColor: colors.surface, borderRadius: 18, padding: 17, ...shadow }, qualityTop: { flexDirection: 'row', justifyContent: 'space-between' }, qualityTitle: { color: colors.ink, fontWeight: '800' }, score: { color: colors.teal, fontWeight: '900', fontSize: 21 }, qualityBody: { color: colors.muted, fontSize: 12, lineHeight: 17, marginTop: 6 }, progress: { height: 8, backgroundColor: colors.canvas, borderRadius: 4, marginTop: 15 }, progressFill: { width: '4%', height: 8, backgroundColor: colors.teal, borderRadius: 4 } });
